CREATE FUNCTION date_check(datatxt VARCHAR(200)) RETURNS text CHARSET utf8
BEGIN
DECLARE wwvar1 CHAR(50) DEFAULT '';
DECLARE wwvar2 CHAR(50) DEFAULT '';
DECLARE wwvar3 CHAR(50) DEFAULT '';
DECLARE pess VARCHAR(200) DEFAULT '';
DECLARE dateopt1 CHAR(50) DEFAULT '';
DECLARE dateopt2 CHAR(50) DEFAULT '';
DECLARE ress CHAR(100) DEFAULT NULL;
DECLARE ress2 CHAR(100) DEFAULT NULL;
DECLARE ress3 CHAR(100) DEFAULT NULL;
DECLARE np1 INT(10) DEFAULT 0;
DECLARE npp INT(10) DEFAULT 0;
DECLARE ncat INT(10) DEFAULT 0;
DECLARE nres INT(10) DEFAULT 0;
DECLARE anlim INT(10) DEFAULT 0;
SELECT REPLACE(TRIM(datatxt),' ',' ') INTO pess;
SELECT REPLACE(TRIM(pess),' ',' ') INTO pess;
SELECT REPLACE(TRIM(pess),' ','#') INTO pess;
SELECT REPLACE(TRIM(pess),'.',' ') INTO pess;
SELECT REPLACE(TRIM(pess),',',' ') INTO pess;
SELECT REPLACE(TRIM(pess),'/',' ') INTO pess;
SELECT REPLACE(TRIM(pess),'-',' ') INTO pess;
SELECT REPLACE(TRIM(pess),'_',' ') INTO pess;
SELECT REPLACE(TRIM(pess),';',' ') INTO pess;
SELECT REPLACE(TRIM(pess),' ',' ') INTO pess;
SELECT REPLACE(TRIM(pess),' ',' ') INTO pess;
SELECT REPLACE(pess,'#',' ') INTO pess;
SELECT REPLACE(TRIM(pess),' ',' ') INTO pess;
SELECT REPLACE(TRIM(pess),' ',' ') INTO pess;
SELECT substrCount(pess,' ')+1 INTO ncat;
IF (ncat=3) THEN
SELECT YEAR(CURDATE()) INTO anlim;
SELECT TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(pess,' ',1),' ',-1)) INTO wwvar1;
SELECT TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(pess,' ',2),' ',-1)) INTO wwvar2;
SELECT TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(pess,' ',3),' ',-1)) INTO wwvar3;
SELECT CHAR_LENGTH(wwvar1) INTO np1;
SELECT CHAR_LENGTH(wwvar3) INTO npp;
SELECT CONCAT(wwvar1,'-',wwvar2,'-',wwvar3) INTO pess;
IF (npp=4 OR (np1<=2 AND npp<=2)) THEN
SELECT STR_TO_DATE(pess,'%d-%m-%Y') INTO ress;
IF (ress IS NOT NULL AND YEAR(ress)>anlim) THEN
SET ress = NULL;
ELSE
IF (ress IS NOT NULL) THEN
SET nres = nres+1;
END IF;
END IF;
END IF;
IF (np1=4 OR (np1<=2 AND npp<=2)) THEN
SELECT STR_TO_DATE(pess,'%Y-%m-%d') INTO ress2;
IF (ress2 IS NOT NULL AND YEAR(ress2)>anlim) THEN
SET ress2 = NULL;
ELSE
IF (ress2 IS NOT NULL) THEN
SET nres = nres+1;
END IF;
END IF;
END IF;
END IF;
IF (nres=1) THEN
IF (ress2 IS NOT NULL) THEN
RETURN ress2;
END IF;
RETURN ress;
ELSE
SELECT STR_TO_DATE(pess,'%m-%d-%Y') INTO ress;
IF (ress IS NOT NULL AND YEAR(ress)>anlim) THEN
SET ress = NULL;
END IF;
IF (ress IS NULL) THEN
SELECT STR_TO_DATE(pess,'%Y-%d-%m') INTO ress;
IF (ress IS NOT NULL AND YEAR(ress)>anlim) THEN
SET ress = NULL;
END IF;
END IF;
RETURN ress;
END IF;
END
