CREATE FUNCTION habitaclasse(habtid int(10)) RETURNS VARCHAR(500) CHARSET utf8
BEGIN
DECLARE done INT DEFAULT 0;
DECLARE respar TEXT DEFAULT '';
DECLARE resultado TEXT DEFAULT '';
DECLARE lixo TEXT DEFAULT '';
DECLARE contador INT DEFAULT 0;
DECLARE tvariation TEXT DEFAULT '';
DECLARE tname TEXT DEFAULT '';
DECLARE tunit TEXT DEFAULT '';
DECLARE clname TEXT DEFAULT '';
DECLARE toprint TEXT DEFAULT '';
DECLARE cur1 CURSOR FOR SELECT hab.PathName FROM Habitat as hab WHERE HabitatID=habtid;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
OPEN cur1;
loop1: LOOP
FETCH cur1 INTO tvariation;
IF done=1 THEN
CLOSE cur1;
LEAVE loop1;
END IF;
SET resultado = tvariation;
END LOOP loop1;
RETURN resultado;
END
