CREATE FUNCTION checkangulo(angu VARCHAR(200)) RETURNS FLOAT
BEGIN
DECLARE yyll CHAR(10) DEFAULT '';
DECLARE yyan FLOAT DEFAULT NULL;
DECLARE ress FLOAT DEFAULT NULL;
SELECT TRIM(REPLACE(TRIM(angu),',','.')) INTO yyll;
IF (yyll>'') THEN
SELECT TRIM(yyll)+0 INTO yyan;
IF (yyan>360 OR yyan<0) THEN
SET ress = NULL;
ELSE
SET ress = yyan;
END IF;
END IF;
RETURN ress;
END
